config/routes.rb
Rails.application.routes.draw do
  resources :sneakers do
    resources :reviews
  end
  post 'site/add', as: :add
  post 'site/remove', as: :remove
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resource :cart, only: [:show]
  scope 'cart/:sneaker_id' do
    post 'add', to: 'line_items#update', as: :add_to_cart
    delete 'remove', to: 'line_items#destroy', as: :remove_from_cart
  end
  # Defines the root path route ("/")
  root "sneakers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include ActionView::RecordIdentifier
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy
  has_many :sneakers, through: :line_items


  def add_sneaker(sneaker)
    item = find_item(sneaker)

    unless item
      item = line_items.build(sneaker_id: sneaker.id)
    end

    item.increment(:quantity)
    item
  end

  def remove_sneaker(sneaker)
    item = find_item(sneaker)

    if item
      item.decrement(:quantity) if item.quantity > 0
    end
    item.destroy if item.quantity.zero?
    item
  end

  def total_price
    line_items.sum(&:total_price)
  end

  def sneaker_count(sneaker)
    line_items.find_by(sneaker_id: sneaker.id)&.quantity || 0
  end

  private
  def find_item(sneaker)
    line_items.find_by(sneaker_id: sneaker.id)
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :sneaker
  belongs_to :cart

  def total_price
    sneaker.price * quantity
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :sneaker
  validates :body, presence: true

  after_destroy_commit -> { broadcast_remove_to [sneaker, :reviews], target: self }
  after_create_commit :broadcast_create
  after_update_commit :broadcast_update

  def broadcast_create
    broadcast_append_to(
        [sneaker, :reviews],
        partial: 'reviews/simple_review',
        target: dom_id(sneaker, :reviews),
        locals: {review: self }
    )
  end

  def broadcast_update
    broadcast_replace_later_to(
      [sneaker, :reviews],
      partial: 'reviews/simple_review',
      locals: {review: self }
    )
  end
end

app/models/sneaker.rb
class Sneaker < ApplicationRecord
  has_one_attached :image
  has_many :reviews
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_one :cart
  after_create :create_cart


  private

  def create_cart
    self.cart = Cart.create!(user_id: self .id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/authed_controller.rb
class AuthedController < ApplicationController
  before_action :require_login
  before_action :set_cart

  private
  def set_cart
    puts "SET CAR RAN"
    @cart ||= Cart.find_or_create_by(user_id: current_user.id)
  end
end

app/controllers/carts_controller.rb
class CartsController < AuthedController
end

app/controllers/line_items_controller.rb
class LineItemsController < AuthedController
  before_action :set_sneaker

  def update
    @line_item = @cart.add_sneaker(@sneaker)
    @line_item.save
  end

  def destroy
    @line_item = @cart.remove_sneaker(@sneaker)
    @line_item.save
  end

  private
  def  set_sneaker
    @sneaker = Sneaker.find(params[:sneaker_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < AuthedController
  before_action :set_sneaker
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = @sneaker.reviews.order(:created_at)
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = @sneaker.reviews.new(review_params.merge(user_id: current_user.id))

    respond_to do |format|
      @review.save
      format.turbo_stream
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    if @review.update(review_params)
      render turbo_stream: turbo_stream.replace(@review, @review)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@review) }
    end
  end

  private

  def set_sneaker
    @sneaker = Sneaker.find(params[:sneaker_id])
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def review_params
    params.require(:review).permit(:user_id, :sneaker_id, :body, :rating)
  end
end

app/controllers/site_controller.rb
class SiteController < AuthedController
  before_action :set_count, only: :index
  def index
    @count = session[:count]
  end

  def add
    @count = session[:count] += 1
  end

  def remove
    @count = session[:count] -= 1
  end


  private

  def set_count
    session[:count] = 0
  end
end

app/controllers/sneakers_controller.rb
class SneakersController < AuthedController
  before_action :set_sneaker, only: %i[ show edit update destroy ]

  # GET /sneakers or /sneakers.json
  def index
    @sneakers = Sneaker.all
  end

  # GET /sneakers/1 or /sneakers/1.json
  def show
  end

  # GET /sneakers/new
  def new
    @sneaker = Sneaker.new
  end

  # GET /sneakers/1/edit
  def edit
  end

  # POST /sneakers or /sneakers.json
  def create
    @sneaker = Sneaker.new(sneaker_params)

    respond_to do |format|
      if @sneaker.save
        format.html { redirect_to sneaker_url(@sneaker), notice: "Sneaker was successfully created." }
        format.json { render :show, status: :created, location: @sneaker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sneakers/1 or /sneakers/1.json
  def update
    respond_to do |format|
      if @sneaker.update(sneaker_params)
        format.html { redirect_to sneaker_url(@sneaker), notice: "Sneaker was successfully updated." }
        format.json { render :show, status: :ok, location: @sneaker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sneakers/1 or /sneakers/1.json
  def destroy
    @sneaker.destroy

    respond_to do |format|
      format.html { redirect_to sneakers_url, notice: "Sneaker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sneaker
      @sneaker = Sneaker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sneaker_params
      params.require(:sneaker).permit(:name, :brand, :description, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authed_helper.rb
module AuthedHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sneakers_helper.rb
module SneakersHelper
end

app/views/carts/_cart.html.erb
<%= turbo_frame_tag @cart do%>
    <details class="relative cursor-pointer z-50">
      <summary>
        <%= number_to_currency(@cart.total_price) %>
      </summary>
      <div class="absolute right-0 w-96 p-2 bg-white shadow-md rounded-b-lg">
        <div class="divide-y divide-gray-300 p-2">
          <%= render  @cart.line_items %>
        </div>
        <div class="flex justify-between font-black border-t-2 border-gray-500 p-2">
          <span class="">Subtotal:</span>
          <span><%= number_to_currency(@cart.total_price) %></span>
        </div>
      </div>
    </details>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>Sneakerr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body class="h-full antialised container mx-auto">
    <header class="py-5 border-b border-gray-100 flex justify-between sticky top-0 bg-white z-10">
      <h1 class="font-bold text-3xl">
        <%= link_to 'Snikerr', root_path %>
      </h1>

      <div class="flex text-sm gap-5">
        <% if signed_in? %>
          <%= render 'carts/cart' %>
          <span><%= current_user.email %></span>
          <%= button_to 'Sign out', sign_out_path, method: :delete %>
        <% else %>
            <%= link_to 'Login', sign_in_path %>
            <%= link_to 'Register', sign_up_path %>

        <% end %>
      </div>
    </header>
    <main class="py-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/line_items/_line_item.html.erb
<div class="flex gap-5 p-2 ">
  <div class="bg-gray-100 px-2 rounded">
    <%= line_item.quantity %>
  </div>
  <div>
    <%= line_item.sneaker.name %>
  </div>
  <div class="ml-auto text-green-600">
    <%= number_to_currency(line_item.total_price) %>
  </div>
</div>

app/views/line_items/destroy.turbo_stream.erb
<%= turbo_stream.update(@cart, partial: 'carts/cart') %>
<%= turbo_stream.update(dom_id(@sneaker, :items_in_cart), partial: 'sneakers/count', locals: {sneaker: @sneaker}) %>

app/views/line_items/update.turbo_stream.erb
<%= turbo_stream.update(@cart, partial: 'carts/cart') %>
<%= turbo_stream.update(dom_id(@sneaker, :items_in_cart), partial: 'sneakers/count', locals: {sneaker: @sneaker}) %>

app/views/reviews/_form.html.erb
<%= form_with(model: [@sneaker, review], class: "contents") do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rating %>
    <%= form.range_field :rating, min:0, max: 5,  class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<%= turbo_frame_tag dom_id(review) do %>
  <div class="p-5 border border-gray-100 text-sm mt-5">
    <h3 class="font-bold"><%= time_ago_in_words(review.created_at) %></h3>

    <div>
      <%= review.body %>
    </div>

    <div class="flex gap-5 mt-5">
      <% if review.user == current_user %>
        <%= link_to 'Edit', edit_sneaker_review_path(review.sneaker, review), class: 'border-2 px-3 py-2 border-green-600 text-green-600 rounded hover:bg-green-600 hover:text-gray-100' %>
        <%= button_to 'Delete', sneaker_review_path(review.sneaker, review), method: :delete, class: 'border-2 px-3 py-2 border-red-600 text-red-600 rounded hover:bg-red-600 hover:text-gray-100' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/reviews/_simple_review.html.erb
<%= turbo_frame_tag dom_id(review) do %>
  <div class="p-5 border border-gray-100 text-sm mt-5">
    <h3 class="font-bold"><%= time_ago_in_words(review.created_at) %></h3>

    <div>
      <%= review.body %>
    </div>
  </div>
<% end %>

app/views/reviews/create.turbo_stream.erb
<% if @review.persisted? %>
  <%= turbo_stream.replace(dom_id(@sneaker, :review_form), partial: "form", locals: {review: @sneaker.reviews.new}) %>
  <%= turbo_stream.append(dom_id(@sneaker, :reviews), partial: "review", locals: {review: @review}) %>
<% end %>

app/views/reviews/edit.html.erb
<%= turbo_frame_tag dom_id(@review) do %>
  <%= link_to 'Cancel', sneaker_review_path(@review.sneaker, @review),class: 'float-right' %>
  <%= render "form", review:@review %>
<% end %>

app/views/reviews/index.html.erb
<%= turbo_frame_tag dom_id(@sneaker, :reviews) do %>
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Reviews</h1>
    <%= link_to 'New review', new_sneaker_review_path(@sneaker), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="reviews" class="min-w-full">
    <%= render @reviews %>
  </div>
</div>
<% end %>

app/views/reviews/new.html.erb
<%= turbo_frame_tag dom_id(@sneaker, :review_form) do %>
<div class="mx-auto md:w-2/3 w-full">

  <%= render "form", review: @review %>
</div>
<% end %>

app/views/reviews/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @review %>

    <%= link_to 'Edit this review', edit_sneaker_review_path(@review), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this review', sneaker_review_path(@review), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to reviews', sneaker_reviews_path(@review.sneaker, @review), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/site/_count.html.erb
<div class="<%= op == :add ? 'text-green-500' : 'text-red-500' %>">
  <%= op == :add ? 'Added' : 'Removed' %> an Apple
</div>

app/views/site/add.turbo_stream.erb
<%= turbo_stream.update('count', pluralize(@count, 'apple')) %>
<%= turbo_stream.append('log', partial: 'count', locals: {op: :add}) %>

app/views/site/add_turbo_stream.erb
<%= turbo_stream.update('count', pluralize(@count, 'apple')) %>

app/views/site/index.html.erb
<div class="block">
  <h1>Apples counter</h1>
  <div id="count">

    <h1 class="font-bold"> Apples: <%= @count %></h1>
  </div>
  <div class="flex gap-5 mt-5">
    <%= button_to 'Add', add_path, class: 'p-2 bg-blue-500 text-blue-200 rounded-md' %>
    <%= button_to 'Remove', remove_path, class: 'p-2 bg-red-500 text-red-200 rounded-md' %>
  </div>

  <div id="log" class="mt-5">
    This is the log
  </div>
</div>

app/views/site/remove.turbo_stream.erb
<%= turbo_stream.update('count', pluralize(@count, 'apple')) %>
<%= turbo_stream.append('log', partial: 'count', locals: {op: :remove}) %>

app/views/site/remove_turbo_stream.erb
<%= turbo_stream.update('count', pluralize(@count, 'apple')) %>

app/views/sneakers/_count.html.erb
<span class="absolute right-2 top-2 flex justify-center gap-2 bg-gray-700 text-gray-300 text-sm rounded-full p-2">
  <%= button_to '+', add_to_cart_path(sneaker), method: :post %>
  <span><%= @cart.sneaker_count(sneaker) %></span>
  <%= button_to '_', remove_from_cart_path(sneaker), method: :delete %>
</span>

app/views/sneakers/_form.html.erb
<%= form_with(model: sneaker, class: "contents") do |form| %>
  <% if sneaker.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(sneaker.errors.count, "error") %> prohibited this sneaker from being saved:</h2>

      <ul>
        <% sneaker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :brand %>
    <%= form.text_field :brand, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/sneakers/_sneaker.html.erb
<div id="<%= dom_id sneaker %>", class="border border-gray-300 rounded-lg p-2 relative">
  <%= turbo_frame_tag dom_id(sneaker, :items_in_cart) do %>
    <%= render partial: 'count', locals: {sneaker: } %>
  <% end %>
  <%= link_to sneaker_path(sneaker) do %>
    <div class="rounded-t-lg bg-white">
      <%= image_tag sneaker.image, class: 'rounded mx-auto' if sneaker.image.attached? %>

    </div>

    <div class="py-5">
      <div class="flex justify-between">
        <h2 class="font-bold"><%= sneaker.name %></h2>
        <span class="font-bold text-green-500"><%= number_to_currency(sneaker.price) %></span>
      </div>
    </div>
    <div class="text-gray-500 text-xs">
      <%= sneaker.brand %>
    </div>

    <p class="text-gray-700 text-sm"><%= sneaker.description %></p>
  <% end %>

  <div class="p-2">
    <%= button_to add_to_cart_path(sneaker_id: sneaker.id), method: :post, class: 'btn-primary w-full' do  %>
      Add to cart
    <% end %>
  </div>
</div>

app/views/sneakers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing sneaker</h1>

  <%= render "form", sneaker: @sneaker %>

  <%= link_to "Show this sneaker", @sneaker, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to sneakers", sneakers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sneakers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Sneakers</h1>
    <%= link_to 'New sneaker', new_sneaker_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="sneakers" class="mt-10 grid grid-cols-3 gap-10">
    <%= render @sneakers %>
  </div>
</div>

app/views/sneakers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New sneaker</h1>

  <%= render "form", sneaker: @sneaker %>

  <%= link_to 'Back to sneakers', sneakers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sneakers/show.html.erb
<%= turbo_stream_from [@sneaker, :reviews] %>
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
<% end %>

<div class="flex gap-5">
  <div>
    <%= render @sneaker %>
  </div>

  <div class="w-1/3">
    <%= turbo_frame_tag dom_id(@sneaker, :reviews), src: sneaker_reviews_path(@sneaker)%>
    <%= turbo_frame_tag dom_id(@sneaker, :review_form), src: new_sneaker_review_path(@sneaker)%>

  </div>
</div>
<div class="inline-block ml-2">
  <%= link_to 'Edit this sneaker', edit_sneaker_path(@sneaker), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= button_to 'Destroy this sneaker', sneaker_path(@sneaker), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
</div>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.email_field :email %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>